# Generated by Django 5.2 on 2025-05-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Editora',
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.editora'),
            preserve_default=False,
        ),
    ]
