# Generated by Django 5.2 on 2025-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_autor_editora_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Autor',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
    ]
