# Generated by Django 5.2 on 2025-04-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_livro_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
